### ISSUE TITLE
Build failure with OpenSSL 1.1.1c on macOS

### ISSUE THREAD

**Issue by fxcoudert** [osquery/osquery#5755]
# Bug report

### What operating system and version are you using?

macOS, all versions from 10.12 to 10.14

### What version of osquery are you using?

osquery 3.3.2

### What steps did you take to reproduce the issue?

Trying to build with OpenSSL 1.1.1c on macOS, we get the following build error:

```
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:45:36: error: member access into incomplete type 'X509' (aka 'x509_st')
  r["key_usage"] = genKeyUsage(cert->ex_kusage);
                                   ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:47:12: error: member access into incomplete type 'X509' (aka 'x509_st')
      (cert->akid && cert->akid->keyid)
           ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:48:32: error: member access into incomplete type 'X509' (aka 'x509_st')
          ? genKIDProperty(cert->akid->keyid->data, cert->akid->keyid->length)
                               ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:48:57: error: member access into incomplete type 'X509' (aka 'x509_st')
          ? genKIDProperty(cert->akid->keyid->data, cert->akid->keyid->length)
                                                        ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:51:12: error: member access into incomplete type 'X509' (aka 'x509_st')
      (cert->skid) ? genKIDProperty(cert->skid->data, cert->skid->length) : "";
           ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:51:41: error: member access into incomplete type 'X509' (aka 'x509_st')
      (cert->skid) ? genKIDProperty(cert->skid->data, cert->skid->length) : "";
                                        ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
/tmp/osquery-20190906-38097-5jyoer/osquery-3.3.2/osquery/tables/system/darwin/certificates.mm:51:59: error: member access into incomplete type 'X509' (aka 'x509_st')
      (cert->skid) ? genKIDProperty(cert->skid->data, cert->skid->length) : "";
                                                          ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
7 errors generated.
```

The exact same build using OpenSSL 1.0.0s succeeds.

**Comment by fxcoudert** [comment]
This is the patch I came up with, which fully fixes the build on macOS:

```
diff -pur osquery-3.3.2/osquery/tables/system/darwin/certificates.mm osquery-3.3.2-fixed/osquery/tables/system/darwin/certificates.mm
--- osquery-3.3.2/osquery/tables/system/darwin/certificates.mm	2018-10-29 22:24:29.000000000 +0100
+++ osquery-3.3.2-fixed/osquery/tables/system/darwin/certificates.mm	2019-09-07 16:25:24.000000000 +0200
@@ -20,6 +20,7 @@ namespace tables {
 
 void genCertificate(X509* cert, const std::string& path, QueryData& results) {
   Row r;
+  const ASN1_OCTET_STRING *s;
 
   // Generate the common name and subject.
   // They are very similar OpenSSL API accessors so save some logic and
@@ -42,13 +43,11 @@ void genCertificate(X509* cert, const st
   // so it should be called before others.
   r["ca"] = (CertificateIsCA(cert)) ? INTEGER(1) : INTEGER(0);
   r["self_signed"] = (CertificateIsSelfSigned(cert)) ? INTEGER(1) : INTEGER(0);
-  r["key_usage"] = genKeyUsage(cert->ex_kusage);
-  r["authority_key_id"] =
-      (cert->akid && cert->akid->keyid)
-          ? genKIDProperty(cert->akid->keyid->data, cert->akid->keyid->length)
-          : "";
-  r["subject_key_id"] =
-      (cert->skid) ? genKIDProperty(cert->skid->data, cert->skid->length) : "";
+  r["key_usage"] = genKeyUsage(X509_get_key_usage(cert));
+  s = X509_get0_authority_key_id(cert);
+  r["authority_key_id"] = s ? genKIDProperty(s->data, s->length) : "";
+  s = X509_get0_subject_key_id(cert);
+  r["subject_key_id"] = s ? genKIDProperty(s->data, s->length) : "";
 
   r["serial"] = genSerialForCertificate(cert);
 
diff -pur osquery-3.3.2/osquery/tables/system/darwin/keychain_utils.cpp osquery-3.3.2-fixed/osquery/tables/system/darwin/keychain_utils.cpp
--- osquery-3.3.2/osquery/tables/system/darwin/keychain_utils.cpp	2018-10-29 22:24:29.000000000 +0100
+++ osquery-3.3.2-fixed/osquery/tables/system/darwin/keychain_utils.cpp	2019-09-07 17:03:59.000000000 +0200
@@ -84,7 +84,10 @@ void genAlgorithmProperties(X509* cert,
                             std::string& sig,
                             std::string& size) {
   int nid = 0;
-  nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
+  ASN1_OBJECT *ppkalg;
+  X509_PUBKEY *pubkey = X509_get_X509_PUBKEY(cert);
+  X509_PUBKEY_get0_param(&ppkalg, NULL, NULL, NULL, pubkey);
+  nid = OBJ_obj2nid(ppkalg);
   if (nid != NID_undef) {
     key = std::string(OBJ_nid2ln(nid));
 
@@ -101,7 +104,7 @@ void genAlgorithmProperties(X509* cert,
       // The EVP_size for EC keys returns the maximum buffer for storing the
       // key data, it does not indicate the size/strength of the curve.
       if (nid == NID_X9_62_id_ecPublicKey) {
-        const EC_KEY* ec_pkey = pkey->pkey.ec;
+        const EC_KEY* ec_pkey = EVP_PKEY_get0_EC_KEY(pkey);
         const EC_GROUP* ec_pkey_group = nullptr;
         ec_pkey_group = EC_KEY_get0_group(ec_pkey);
         int curve_nid = 0;
@@ -114,7 +117,7 @@ void genAlgorithmProperties(X509* cert,
     EVP_PKEY_free(pkey);
   }
 
-  nid = OBJ_obj2nid(cert->cert_info->signature->algorithm);
+  nid = OBJ_obj2nid(X509_get0_tbs_sigalg(cert)->algorithm);
   if (nid != NID_undef) {
     sig = std::string(OBJ_nid2ln(nid));
   }
```

It uses functions to access members of types that have been made opaque in OpenSSL 1.1.

**Comment by directionless** [comment]
We're just in the process of completely reworking the build and dependency system. 

But, it looks like the openssl version is 1.0.2o. https://github.com/osquery/osquery/blob/e6fe15eb49660725e65dba1549932ed96e0a8c6e/third-party/openssl/osquery.library#L3

Maybe something we should try to bump before we cut 4.0.1? (@alessandrogario ?)

**Comment by fxcoudert** [comment]
You could support both versions easily with conditionals on `OPENSSL_VERSION_NUMBER`.
OpenSSL 1.0 will hit end-of-life on 2019-12-31, so it makes sense to move now :)

Homebrew, probably like other distributions, links with its owns openssl rather than letting each package build their own out-of-date version. For example, OpenSSL 1.0.2o is affected by 6 CVEs, including one of “moderate severity” (the latest version is 1.0.2s).

**Comment by theopolis** [comment]
Thanks for all of the work here @fxcoudert, we will apply the changes and migrate soon. The use of OpenSSL within osquery should not be effected by the known issues. We will not be able to apply to perform the migration this week but will we track this as high-pri for the 4.0.2 release.

**Comment by alessandrogario** [comment]
[PR 5928](https://github.com/osquery/osquery/pull/5928) upgrades the library from **1.0.2o** to **1.0.2t**, and enables its [**formula**](https://github.com/osquery/osquery/tree/3e1dd14d8dbe17570cde2cfc9707514378e433a4/libraries/cmake/formula) for all operating systems.

It is not possible to upgrade further since that would cause linking issues with all the pre-built libraries we are currently still fetching from the [**facebook** layer](https://github.com/osquery/osquery/tree/3e1dd14d8dbe17570cde2cfc9707514378e433a4/libraries/cmake/facebook) when building on macOS and Windows.

I've moved this issue to the next milestone
