### ISSUE TITLE
Intel MacOS build Osquery failed with error: no member named 'global_seq_num' in 'es_message_t'

### ISSUE THREAD

**Issue by hp2011gun** [osquery/osquery#7825]
After config is done, when build osquery get error below:

[ 55%] Built target osquery_logger_datalogger
[ 55%] Building CXX object osquery/events/CMakeFiles/osquery_events.dir/darwin/endpointsecurity_fim.cpp.o
[ 55%] Building CXX object osquery/devtools/CMakeFiles/osquery_devtools.dir/shell.cpp.o
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/CarrierGatewayState.cpp.o
/Users/shijunyan/Documents/code/osquery/osquery/events/darwin/endpointsecurity.cpp:102:35: error: no member named 'global_seq_num' in 'es_message_t'
    ec->global_seq_num = message->global_seq_num;
                         ~~~~~~~  ^
1 error generated.
make[2]: *** [osquery/events/CMakeFiles/osquery_events.dir/darwin/endpointsecurity.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 55%] Building CXX object plugins/config/CMakeFiles/plugins_config_filesystemconfig.dir/filesystem_config.cpp.o
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/CertificateAuthentication.cpp.o
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/CertificateAuthenticationRequest.cpp.o
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/CidrAuthorizationContext.cpp.o
[ 55%] Building CXX object plugins/config/CMakeFiles/plugins_config_updateconfigplugin.dir/update.cpp.o
[ 55%] Building CXX object plugins/config/CMakeFiles/plugins_config_tlsconfig.dir/tls_config.cpp.o
[ 55%] Linking CXX static library libosquery_core_init.a
[ 55%] Built target osquery_core_init
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/CidrBlock.cpp.o
[ 55%] Building CXX object libs/src/aws-sdk-cpp/CMakeFiles/thirdparty_aws-cpp-sdk-ec2.dir/src/aws-sdk-cpp/aws-cpp-sdk-ec2/source/model/ClassicLinkDnsSupport.cpp.o
/Users/shijunyan/Documents/code/osquery/osquery/events/darwin/endpointsecurity_fim.cpp:160:35: error: no member named 'global_seq_num' in 'es_message_t'
    ec->global_seq_num = message->global_seq_num;
                         ~~~~~~~  ^
1 error generated.
make[2]: *** [osquery/events/CMakeFiles/osquery_events.dir/darwin/endpointsecurity_fim.cpp.o] Error 1
make[1]: *** [osquery/events/CMakeFiles/osquery_events.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....


Is there anything wrong?

**Comment by mike-myers-tob** [comment]
> /Users/shijunyan/Documents/code/osquery/osquery/events/darwin/endpointsecurity_fim.cpp:160:35: error: no member named 'global_seq_num' in 'es_message_t'
ec->global_seq_num = message->global_seq_num;

This error suggests to me that maybe the version of XCode or the targeted macOS version in the CMake configure step were not correct, or you are trying to build on a macOS host older than macOS 10.15. Refer to the build instructions on the wiki, https://osquery.readthedocs.io/en/latest/development/building/#macos

If you believe you have done everything correctly, then try checking out the repo to a new directory and starting over. If this doesn't work, feel free to reopen this issue with additional details.
