### ISSUE TITLE
YARA rules with include paths fail to compile; include path appears mangled

### ISSUE THREAD

**Issue by m4wh6k** [osquery/osquery#7413]
# Bug report

### What operating system and version are you using?
```
$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 11 (bullseye)
   build = 
platform = debian
```

### What version of osquery are you using?
```
$ osqueryi --line "SELECT version from osquery_info;"
version = 5.0.1
```

### What steps did you take to reproduce the issue?
```
# get YARA rules
sudo git clone https://github.com/Yara-Rules/rules.git /etc/osquery/yara
# check that they work with a test with regular yara 4.0.5 (works)
yara /etc/osquery/yara/malware_index.yar /bin/sh 
# check with osquery
osqueryi --line "SELECT * FROM yara WHERE sigfile='/etc/osquery/yara/malware_index.yar' AND path IN (SELECT DISTINCT path FROM processes) AND count > 0;"
```

### What did you expect to see?
Processes that match yara rules

### What did you see instead?
```
W1210 22:23:19.489068 30362 yara.cpp:228] YARA compile error: Compilation errors
W1210 22:23:19.504873 30362 yara.cpp:228] YARA compile error: Compilation errors
W1210 22:23:19.519486 30362 yara.cpp:228] YARA compile error: Compilation errors
W1210 22:23:19.534797 30362 yara.cpp:228] YARA compile error: Compilation errors
```

### More detail
If I do...
```
strace osqueryi --line "SELECT * FROM yara WHERE sigfile='/etc/osquery/yara/malware_index.yar' AND path IN (SELECT DISTINCT path FROM processes) AND count > 0;"
````
... it seems that for some reason the include paths for the rule that `malware_index.yar` includes get mangled. I can see messages like:
```
openat(AT_FDCWD, "/etc/osquery/yara/./malware/./malware/MALW_Torte_ELF.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
```
