### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [osquery/osquery#5266]
After boostorg/system@2fa0a00583a3a7 build fails. See [error log](https://ptpb.pw/KpdL).

```c++
In file included from osquery/tables/applications/posix/prometheus_metrics.cpp:12:
In file included from include/osquery/config.h:18:
In file included from osquery/core/json.h:15:
In file included from include/osquery/system.h:23:
include/osquery/posix/system.h:29:39: error: expected class name
class DropPrivileges : private boost::noncopyable {
                                      ^
In file included from osquery/tables/applications/posix/prometheus_metrics.cpp:12:
In file included from include/osquery/config.h:18:
In file included from osquery/core/json.h:15:
include/osquery/system.h:42:36: error: expected class name
class Initializer : private boost::noncopyable {
                                   ^
```

**Comment by muffins** [comment]
Thanks for reporting! Looks like some updates are needed for us to get to 1.69, I believe we're still on 1.66.
